edition = "2024"
hard_tabs = false
max_width = 120
use_small_heuristics = "Max"
tab_spaces = 2
newline_style = "Unix"
normalize_comments = true
normalize_doc_attributes = true
format_code_in_doc_comments = true
force_multiline_blocks = true
